#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 29 13:15:01 2017

@author: lex
"""
import numpy as np
import pandas as pd

def read_xls_data(filePath):
    """
    Assumes that there is only one header column!
    Header is on row 32 for excel files generated by Ethovision
    Columns have specific/exact names:
        'Movement(Moving / center-point)'
        'X center'
        'Y center'
    !!! only extracts progression segments
    """

    print('reading XLS file ...')
    xls = pd.ExcelFile(filePath)
    
    db = []
    
    for sheet in xls.sheet_names:
        
        print('reading sheet:', sheet)
    
        # read the whole excel file
        tmp = xls.parse(sheet_name = sheet, header = 32)
        
        # select only the progression segment
        selected_rows = tmp.loc[tmp['Movement(Moving / center-point)']==1]
        
        # remove non numeric type from coordinates
        tmp_x = pd.to_numeric(selected_rows['X center'], errors='coerce').dropna()
        tmp_y = pd.to_numeric(selected_rows['Y center'], errors='coerce').dropna()
        
        # need to Transpose because pandas tmp_x and tmp_y contain column values
        # for further computations the format needed is np.array( [[x1,y1],[x2,y2],[xn,yn]] )
        db.append(np.array([tmp_x,tmp_y]).T)

    return(db)
        
    
if __name__ == '__main__':        
    list_of_coordinates = read_xls_data('../data/Raw data-algea_h2o-Trial     1.xlsx')    